from FPSim2 import FPSim2Engine
import numpy as np
import argparse
import duckdb
import pandas as pd
from pathlib import Path
from dataclasses import dataclass, field
from typing import Sequence
from utils import convert_hac_to_mw, convert_mw_to_hac
from functools import partial
from collections import defaultdict
import datamol as dm
import json
import os
import gc
import pickle as pk
import tables as tb
import atexit
from multiprocessing import Pool


def parse_args():
    parser = argparse.ArgumentParser(description='Search similar SMILES')
    parser.add_argument("-db", "--db_name", type=str, help="the name of the FPSIM2 fingerprint database", required=False, default="Molecular_database/search_db")
    parser.add_argument('-m','--nostereo_database', type=str, help='The folder path for the database where the similes without stereoisomer information is stored', required=False, default='Molecular_database/deduplicate_nostereo')
    parser.add_argument('-ms','--deduplicated_database', type=str, help='The folder path for the deduplicated database with the stereo information', required=False, default='Molecular_database/deduplicate_canonical')
    parser.add_argument('-q','--query_path', type=str, help='File for the query in .smi format', required=True)
    parser.add_argument('-k','--top_k', type=int, help='How many molecular to retrieve (it might return less because of the algorithm)', required=False, default=None)
    parser.add_argument('-t','--threshold', type=float, help='The similarity threshold, faster when higher but it might return less molecules than specified', required=False, default=0.7)
    parser.add_argument('-n','--num_workers', type=int, help='The number of workers for the FPSIM2 search', required=False, default=30)
    parser.add_argument('-i', '--index_file', type=str, help='The index file generated by the nostereo database',  required=False)
    parser.add_argument('-mw', '--mw_range', nargs="+", type=int, help="The MW upper and/or the lower limit whn searching SMILES", default=None, required=False)
    parser.add_argument('-hac', '--hac_limits', nargs="+", type=int, help="The HAC upper and/or lower limit when searching SMILES", default=None, required=False)
    parser.add_argument("-st", "--search_type", required=False, default="similarity", choices=("similarity", "substructure"), help="The type of search to perform")
    parser.add_argument("-ca", "--commercially_avaliable", action="store_true", help="Whether to only retrieve isomers from commercially avaliable databases", required=False)
    parser.add_argument("-cd", "--commercial_databases", nargs="+", type=str, help="The commercial databases to retrieve isomers from if --commercially_avaliable is set", default=["enamine", "wuxi", "mcule", "molport", "zinc"], required=False)
    parser.add_argument('-p','--pairwise_database', type=str, help='The folder path for the pairwise database', required=False, default='Molecular_database/pairwise_analysis')
    parser.add_argument('-cdb', '--cdb_id', type=json.loads, 
                        help='Dictionary mapping commercial database names to their IDs', required=False, 
                        default={"enamine": "001", "wuxi": "014", "mcule": "006", "molport": "013", "zinc": "002"})
    parser.add_argument("-s", "--stage", choices=("search", "retrieve"), default="search", help="Runing search or retrieve")
    parser.add_argument('-ch','--chunk_size', type=int, help='The chunck size for the tanimoto search', required=False, default=150_000)
    args = parser.parse_args()
    return args.db_name, args.nostereo_database, args.index_file, args.top_k, args.threshold, args.num_workers, args.query_path, args.hac_limits, args.mw_range, args.search_type, args.deduplicated_database, args.commercially_avaliable, args.commercial_databases, args.pairwise_database, args.cdb_id, args.stage, args.chunk_size


# ── Worker-global state ─────────────────────────────────────────────────────────
_worker_table = None
_worker_file = None


def _init_worker(h5_path: str) -> None:
    global _worker_table, _worker_file
    _worker_file = tb.open_file(h5_path, mode="r")
    _worker_table = _worker_file.root.fps

    def _cleanup():
        global _worker_file
        if _worker_file is not None and _worker_file.isopen:
            _worker_file.close()

    atexit.register(_cleanup)

def _score_batch(
    batch: np.ndarray,
    query_chunks: np.ndarray,
    threshold: float,
    fp_fields: list[str],
) -> list[tuple[int, float]]:
    """Compute Tanimoto for a small in-memory batch and filter by threshold."""
    db_chunks = np.stack(
        [batch[f] for f in fp_fields], axis=1
    ).astype(np.dtype("<u8"))

    a_and_b = np.bitwise_and(db_chunks, query_chunks)
    a_or_b  = np.bitwise_or(db_chunks,  query_chunks)

    def popcnt_rows(x):
        return np.unpackbits(
            np.ascontiguousarray(x).view(np.uint8), axis=1, bitorder="big"
        ).sum(axis=1, dtype=np.float32)

    scores = popcnt_rows(a_and_b) / popcnt_rows(a_or_b)
    mask = scores >= threshold

    return [
        (int(fp_id), round(float(score), 4))
        for fp_id, score in zip(batch["fp_id"][mask], scores[mask])
    ]


def _process_row_range(
    args: tuple[int, int, int, int, np.ndarray, float, list[str], int]
) -> list[tuple[int, float]]:
    """
    Worker task — streams its OWN row range with where(), scoring in
    bounded-size sub-batches. Never materializes the full range at once.
    """
    start_row, end_row, lower, upper, query_chunks, threshold, fp_fields, sub_chunk_size = args

    colnames = _worker_table.colnames
    dtype    = _worker_table.dtype

    results = []
    buffer = []

    for row in _worker_table.where(
        f"(popcnt >= {lower}) & (popcnt <= {upper})",
        start=start_row, stop=end_row,
    ):
        # MUST extract values now — Row object is invalidated on next iteration
        buffer.append(tuple(row[name] for name in colnames))

        if len(buffer) >= sub_chunk_size:
            batch = np.array(buffer, dtype=dtype)
            results.extend(_score_batch(batch, query_chunks, threshold, fp_fields))
            buffer = []  # free memory immediately

    if buffer:  # flush remainder
        batch = np.array(buffer, dtype=dtype)
        results.extend(_score_batch(batch, query_chunks, threshold, fp_fields))

    return results

@dataclass
class ManualTanimoto:
    h5_path: str
    n_workers: int = 4
    chunk_size: int = 150_000
    fp_type: str = "ecfp"

    def smiles_to_query_chunks(self, smiles: str, **finger_params) -> tuple[np.ndarray, int]:
        """
        Convert SMILES to uint64 chunks compatible with FPSim2 DB.

        Returns
        -------
        chunks : shape (fp_size//64,) dtype little-endian uint64
        popcnt : int
        """
        mol  = dm.to_mol(smiles)
        bits = dm.to_fp(mol, fp_type=self.fp_type, **finger_params)
        bits = (bits > 0).astype(np.uint8)

        chunks = (
            np.packbits(bits, bitorder="big")
            .view(np.dtype(">u8"))    # declare as big-endian
            .astype(np.dtype("<u8"))  # convert to little-endian to match DB
        )
        return chunks, int(bits.sum())
    
    def get_info_from_db(self, h5_path: str) -> int:
        """Read the true fingerprint bit size from the FPSim2 file metadata."""
        with tb.open_file(h5_path, "r") as f:
            dtype = f.root.fps.dtype
            finger_params = f.root.config[1]
        fp_fields = [name for name in dtype.names if name not in ("fp_id", "popcnt")]
        return fp_fields, finger_params

    @classmethod
    def bitbounds(cls, query_popcnt: int, threshold: float) -> tuple[int, int]:
        """
        Compute popcnt lower and upper bounds for a given threshold.
        Any result must satisfy: lower <= popcnt_db <= upper.
        """
        lower = int(np.floor(threshold * query_popcnt))
        upper = int(np.ceil(query_popcnt / threshold))
        return lower, upper
    
    def _row_ranges(self) -> list[tuple[int, int]]:
        """Split the table into n_workers contiguous row ranges (not by candidate count)."""
        with tb.open_file(self.h5_path, mode="r") as f:
            n_rows = f.root.fps.shape[0]

        bounds = np.linspace(0, n_rows, self.n_workers + 1, dtype=np.int64)
        return list(zip(bounds[:-1].tolist(), bounds[1:].tolist()))
    
    def tanimoto_search(
        self,
        smiles: str,
        threshold: float = 0.7,
    ) -> list[tuple[int, float]]:
        """
        Memory-bounded parallel Tanimoto search.
        Each worker streams its own row range — never materializes the full
        filtered set, regardless of how many billions of rows match.
        """
        fp_fields, finger_params = self.get_info_from_db(self.h5_path)
        query_chunks, query_popcnt = self.smiles_to_query_chunks(smiles, **finger_params)
        lower, upper = self.bitbounds(query_popcnt, threshold)

        ranges = self._row_ranges()
        print(f"Query popcnt: {query_popcnt}, popcnt range: [{lower}, {upper}]")
        print(f"Workers: {self.n_workers}, row ranges: {len(ranges)}")

        args = [(start, end, lower, upper, query_chunks, threshold, fp_fields, self.chunk_size)
            for start, end in ranges]

        with Pool(processes=self.n_workers, initializer=_init_worker, initargs=(self.h5_path,)) as pool:
            chunk_results = pool.map(_process_row_range, args, chunksize=1)

        results = sorted(
            [hit for chunk in chunk_results for hit in chunk],
            key=lambda x: -x[1],
        )
        print(f"Hits above {threshold}: {len(results)}")
        return results


@dataclass
class FPSim2Query:
    db_name: str
    query: str | list[str] # has to be SMILES
    workers: int=4
    
    @property
    def queries(self) -> list[str]:
        if isinstance(self.query, str):
            return [self.query]
        return self.query
    
    def similarity_search(
        self,
        threshold: float = 0.7,
        chunk_size=150_000,
        fp_type: str = "ecfp",
            ):
        """Perform similarity search using FPSIM2"""
        search = {}
        fpe = ManualTanimoto(self.db_name, self.workers, chunk_size, fp_type)
        for que in self.queries:
            search[que] = fpe.tanimoto_search(que, threshold=threshold)
            
        return search
    
    def substructure_screenout(
        self):
        """Perform substructure search using FPSIM2"""
        
        search = {}
        fpe = FPSim2Engine(self.db_name)

        for que in self.queries:
            results = fpe.substructure(que, n_workers=self.workers)
            search[que] = [int(x) for x in results]

        return search


@dataclass
class SmilesRetriever:
    """
    Retrieve smiles based on indexes from FPSIM2 search results and filter based on HAC or molecular weight range.
    
    Parameters
    -----------
    index_file: str
        The index file generated by deduplication which tells the size of each HAC
    database_path: str
        The folder path for the analoguous search database
    mw_range: Iterable[float] | None = None
        The range of molecular weights to filter. The first number is the lower bound and the second is the upper bound
    hac_limits: Iterable[int] | None = None
        The range of HACs to filter. The first number is the lower bound and the second is the upper bound.
    
    Only one of mw_range or hac_limits can be specified
    """
    index_file: str
    database_path: str
    mw_range: Sequence[float|int] | None = None
    hac_limits: Sequence[int] | None = (4, 80)
    
    @property
    def upper(self) -> int | None:
        if self.hac_limits is not None and self.mw_range is not None:
            raise ValueError("Only one of mw_range or hac_limits can be specified")
        elif self.hac_limits is not None:
            return self.hac_limits[1]
        elif self.mw_range is not None:
            return convert_mw_to_hac(self.mw_range[1])
        else:
            return None
        
    @property
    def lower(self) -> int | None:
        if self.hac_limits is not None:
            return self.hac_limits[0]
        elif self.mw_range is not None:
            return convert_mw_to_hac(self.mw_range[0])
        else:
            return None
    

    def _filter_hacs(self, hac: int):
        u, l = True, True
        if self.upper is not None:
            u =  hac <= self.upper
        if self.lower is not None:
            l = hac >= self.lower                            
        return all([u, l])
        

    def find_hac_by_index(self, search_results: dict[str, list[int]]) -> dict[str, list[int]]:
        """
        Given the indices of the search results find in which HAC the molecule is found and reduce the scopre when
        retrieving the SMILES strings
        """
        with open(self.index_file, "r") as st:
            lines = {int(x.strip().split("#")[-1]): int(x.split("#")[0].strip("HAC")) for x in st.readlines()}
        index_dict = {}
        bounds = np.array(sorted(lines.keys()))
        for query, result in search_results.items():
            index = sorted([x[0] for x in result])
            i = np.unique(np.searchsorted(bounds, index, side="right"))
            hacs = [lines.get(x) for x in bounds[i]]
            index_dict[query] = hacs
        return index_dict

    def convert_hac_topath(self,
        hac_dict: dict[str, list[int]], 
        ) -> dict[str, list[str]]:
        """
        Convert hac to parquet paths for the duck db read_parquet
        """
        parquet_paths = {}
        for query, hacs in hac_dict.items():
            hacs = filter(self._filter_hacs, hacs)
            parquet_paths[query] = [f"{self.database_path}/HAC_{hac}/*.parquet" for hac in hacs]
        return parquet_paths

    def retrieve_smiles(self,
        db_con: duckdb.DuckDBPyConnection,
        indices: list[int],
        parquet_path: list[str],
        ) -> pd.DataFrame:
        """ 
        Retrieve the SMILES from the databases and convert them into Dataframes
        """
        res = db_con.execute("SELECT nostereo_SMILES, num_ID FROM read_parquet($path) WHERE num_ID IN $indices;", {"path": parquet_path, "indices": indices}).df()
        return res

    def batch_retrieve(
        self,
        search_result: dict[str, list[tuple[int, int]]], 
        parquet_paths: dict[str, list[str]],
        search_type: str ="similarity"
        ) -> dict[str, pd.DataFrame]:
        
        #extract the index from the FPSIM2 results and generate the combined path and indices
        """
        Batch retrieve SMILES and db_id from the database using the results of FPSIM2 search and the parquet file paths
        """
        if search_type == "similarity":
            index = set([mol_id[0] for ind in search_result.values() for mol_id in ind])
        else:
            index = set([mol_id for ind in search_result.values() for mol_id in ind])
        
        parquet = set()
        for i in parquet_paths.values():
            parquet.update(i)
             
        result = {}
        # connect to database and search using the combined indices and parquet files
        db_con = duckdb.connect()   
        res = self.retrieve_smiles(db_con, sorted(index), list(parquet))
        for query, index in search_result.items():
            if not index: continue
            
            if search_type == "substructure":
                dat = res[res["num_ID"].isin(index)]
                result[query] = dat
                
            else:
                index = pd.DataFrame(index)
                index.columns = ["mol_id", "Tanimoto"]
                index["mol_id"] = index["mol_id"].astype(int)
                index.set_index("mol_id", inplace=True)
                dat = res[res["num_ID"].isin(index.index)]
                coeff = index.loc[dat["num_ID"]]["Tanimoto"]
                dat["Tanimoto"] = coeff.values
                
            result[query] = dat
            
        db_con.close()
        return result
    
    def run(self, 
        search_results: dict[str, list[int]],
        search_type: str ="similarity"
        ) -> pd.DataFrame:
        """
        A convenient function to run the similarity search
        """
        hac_dict = self.find_hac_by_index(search_results)
        parquet_paths = self.convert_hac_topath(hac_dict)
        smiles = self.batch_retrieve(search_results, parquet_paths, search_type)
        return smiles


@dataclass
class IsomerRetriever:
    """
    Retrieve isomers from the deduplicated database and optionally
    filter by commercial availability.
    """

    deduplicated_database: str
    pairwise_database: str | None = None

    commercially_available: bool = False
    commercial_databases: Sequence[str] = ("enamine", "wuxi", "mcule", "molport", "zinc")

    db_id: dict[str, str] = field(default_factory=lambda: {
        "enamine": "001",
        "wuxi": "014",
        "mcule": "006",
        "molport": "013",
        "zinc": "002",
    })

    @property
    def commercial_db_codes(self) -> tuple[str, ...]:
        return tuple(self.db_id[name] for name in self.commercial_databases)
    
    
    def run(
        self,
        queries: dict[str, pd.DataFrame],
    ) -> dict[str, pd.DataFrame]:
        """
        Main entry point: retrieve isomers for each query.
        """
        db_con = duckdb.connect()

        try:
            nostereo = pd.concat(queries.values(), axis=0)
            nostereo_smiles = list(set(nostereo["nostereo_SMILES"].to_list()))

            parquet_paths = self._parquet_paths(nostereo_smiles)

            all_isomers = self._query_database(
                db_con,
                nostereo_smiles,
                parquet_paths,
            )

            if self.commercially_available:
                all_isomers = self._filter_commercial_isomers(
                    db_con,
                    all_isomers,
                )

            return self._group_isomers_by_query(queries, all_isomers)

        finally:
            db_con.close()

    def _query_database(
        self,
        db_con: duckdb.DuckDBPyConnection,
        nostereo_smiles: list[str],
        parquet_paths: list[str],
    ) -> pd.DataFrame:
        """
        Retrieve all isomers from the deduplicated database with the nostereo_SMILES list.
        """
        query = """
        SELECT
            ID,
            SMILES,
            nostereo_SMILES,
            db_id
        FROM read_parquet($path)
        WHERE nostereo_SMILES IN $smiles;
        """

        return db_con.execute(query, {"path": parquet_paths, "smiles": nostereo_smiles}).df()

    def _query_pairwise_database(
        self,
        db_con: duckdb.DuckDBPyConnection,
        smiles: list[str],
        parquet_paths: list[str],
    ) -> pd.DataFrame:
        """
        Retrieve SMILES that appear in any commercial database
        according to the pairwise database.
        """
        query = """
        SELECT SMILES, db_ids
        FROM read_parquet($path)
        WHERE
            SMILES IN $smiles
            AND len(list_intersect(
                    string_split(db_ids, ','),
                    $db_codes
                )
            ) > 0;
        """

        return db_con.execute(query, {"path": parquet_paths, 
                                      "smiles": smiles, 
                                      "db_codes": self.commercial_db_codes}).df()

    def _filter_commercial_isomers(
        self,
        db_con: duckdb.DuckDBPyConnection,
        isomers: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Keep:
        - isomers directly from commercial databases
        - non-commercial isomers that have duplicates in commercial DBs
        """

        commercial = isomers[isomers["db_id"].isin(self.commercial_db_codes)]
        non_commercial = isomers[~isomers["db_id"].isin(self.commercial_db_codes)]

        if non_commercial.empty:
            return commercial

        duplicated_commercial = self._find_duplicates_in_commercial_dbs(
            db_con,
            non_commercial,
        )

        return pd.concat([commercial, duplicated_commercial], axis=0)

    def _find_duplicates_in_commercial_dbs(
        self,
        db_con: duckdb.DuckDBPyConnection,
        non_commercial: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        From non-commercial isomers, keep those that exist in
        commercial databases according to the pairwise DB.
        """
        smiles = non_commercial["SMILES"].tolist()
        hacs = self._compute_hacs(smiles)

        parquet_paths = [
            f"{self.pairwise_database}/{hac}/*.parquet"
            for hac in set(hacs)
        ]

        pairwise_hits = self._query_pairwise_database(
            db_con,
            smiles,
            parquet_paths,
        )

        new_commercial = non_commercial[
            non_commercial["SMILES"].isin(pairwise_hits["SMILES"])
        ]
        new_commercial["db_id"] = pairwise_hits.set_index("SMILES").loc[new_commercial["SMILES"]]["db_ids"].values
        return new_commercial

    def _parquet_paths(self, smiles: list[str]) -> list[str]:
        hacs = self._compute_hacs(smiles)
        return [
            f"{self.deduplicated_database}/HAC_{hac}/*.parquet"
            for hac in set(hacs)
        ]

    def _compute_hacs(self, smiles: list[str]) -> list[int]:
        return [
            dm.to_mol(smi).GetNumHeavyAtoms()
            for smi in smiles
        ]

    def _group_isomers_by_query(
        self,
        queries: dict[str, pd.DataFrame],
        all_isomers: pd.DataFrame,
    ) -> dict[str, pd.DataFrame]:
        """
        Return isomers grouped per original query.
        """
        result = {}

        for query, df in queries.items():
            subset = all_isomers[
                all_isomers["nostereo_SMILES"].isin(df["nostereo_SMILES"])
            ]
            tanimoto_lookup = df[["nostereo_SMILES", "Tanimoto"]]
            subset = subset.merge(tanimoto_lookup, how="left", on="nostereo_SMILES").set_index("SMILES").sort_values("Tanimoto", ascending=False)

            result[query] = subset

        return result


def _match_smiles(smi: str, query_mol: dm.Mol) -> bool:
    mol = dm.to_mol(smi)
    return mol.HasSubstructMatch(query_mol)

def match_substructure(queries: str | list[str],
                        df_dict: dict[str, pd.DataFrame],
                        workers: int = 4
                        ) -> dict[str, pd.DataFrame]:
    """Perform substructure matching to filter false positives"""
    subs = {}
    if isinstance(queries, str):
        queries = [queries]
    for que in queries:
        query_mol = dm.to_mol(que)
        mask = dm.parallelized(partial(_match_smiles, query_mol=query_mol), 
                               df_dict[que]["SMILES"], n_jobs=workers, 
                               progress=False, scheduler="threads")
        
        subs[que] = df_dict[que][mask]
        
    return subs


def process_query_by_db(db_name: str, query: str | list[str], 
                        num_workers: int=30, 
                        threshold: float = 0.7, 
                        search_type: str = "similarity",
                        outpath: Path = Path("search_results"),
                        chunk_size=150_000):
    
    task_id = int(os.environ.get('SLURM_ARRAY_TASK_ID', 0))
    array_size = int(os.environ.get('SLURM_ARRAY_TASK_COUNT', 0))
    
    my_chunk = list(Path(db_name).glob("*.h5"))
    if array_size:
        my_chunk = my_chunk[task_id::array_size]
    
    for db in my_chunk:
        db_task = int(db.stem.split('_')[-1]) 
        
        out_pkl = f"{outpath}/search_{db_task}.pkl"
        if Path(out_pkl).exists():
            print(f"Search results for {db} already exists, skipping...")
            continue
        
        fp = FPSim2Query(query=query, db_name=db, workers=num_workers)
        search = {"similarity": partial(fp.similarity_search, threshold=threshold, chunk_size=chunk_size), 
                  "substructure": fp.substructure_screenout}    
        
        search_results = search[search_type]()
        with open(out_pkl, "wb") as js:
            pk.dump(search_results, js)
        
        del fp; gc.collect()


def read_search_results(top_k: None | int = None, 
                        search_type: str = "similarity",
                        outpath: Path = Path("search_results")) -> dict[str, list[tuple[int, int]]]:
    
    if not outpath.exists():
        raise FileNotFoundError("The folder for the search results doesn't exists, check the folder")
    res = {}
    print(f"Reading search results from {outpath}...")
    search_results = defaultdict(list)
    for x in outpath.glob("*.pkl"):
        with open(x, "rb") as js:
            res = pk.load(js) # A dictionary of {query: search results}
        for query, item in res.items():
            search_results[query].extend(item)
    if search_type == "similarity":
        for query, item in search_results.items():
            sort_item = sorted(item, key=lambda x: x[1], reverse=True)
            if top_k is not None:
                sort_item = sort_item[:top_k]
            res[query] = sort_item
        return res
    
    return {query: sorted(item) for query, item in search_results.items()}


def main():
    db_name, molecular_database, index_file, top_k, threshold, num_workers, query_path, hac_limits, mw_range, search_type, deduplicated_database, commercially_avaliable, commercial_databases, pairwise_database, cdb_id, stage,chunk_size = parse_args()
   
    query_path = Path(query_path)
    with open(query_path) as w:
        query = [x.strip() for x in w.readlines()]
        
    outpath = Path(f"{query_path.stem}_search_results")
    outpath.mkdir(exist_ok=True)
    
    match stage:    
        case "search":
            process_query_by_db(db_name, query, num_workers, threshold, search_type, outpath=outpath, chunk_size=chunk_size)
            
        case "retrieve": 
            search_results = read_search_results(top_k, search_type, outpath=outpath)
            retrieve = SmilesRetriever(index_file, molecular_database, mw_range, hac_limits)
            smiles = retrieve.run(search_results, search_type)
            pd.concat(smiles).to_csv(f"{query_path.parent}/{query_path.stem}_nostereo_smiles.csv")
            if search_type == "substructure":
                smiles = match_substructure(query, smiles, num_workers)
            retrieve_isomers = IsomerRetriever(deduplicated_database, pairwise_database, 
                                               commercially_avaliable, 
                                               commercial_databases, cdb_id)
            
            output_file = f"{query_path.parent}/{query_path.stem}_query_results.csv" 
            smiles = pd.concat(retrieve_isomers.run(smiles))
            query_not_indb = list(set(query) - set(smiles.index.unique(0)))
            print(f"{len(query_not_indb)} queries not found in the database, they will be saved in the output with ID, SMILES, db_id and Tanimoto set to 0")
            subset_not_indb = pd.DataFrame({"query": query_not_indb, "ID": 0, "SMILES": 0, "db_id": 0, 
                                   "Tanimoto": 0}).set_index(["query", "SMILES"])
            
            pd.concat([smiles, subset_not_indb]).to_csv(output_file)
            
        case other:
            raise NotImplementedError(f"Unknown stage {other}, expected 'search' or 'retrieve'")
    
if __name__ == "__main__":
    # Run this if this file is executed from command line but not if is imported as API
    main()